server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      database: ${sky.redis.database}
      password: ${sky.redis.password}

#config for mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.mrjello.entity
  configuration:
    #config for mybatis log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #config for mybatis camelize
    map-underscore-to-camel-case: true

#config for pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


logging:
  level:
    top:
      mrjello:
        service: info
        controller: info
        mapper: debug
#    web: trace
#    org:
#      springframework:
#        web: trace
#        boot:
#          web: trace







